# Site settings
baseurl = "http://ranchblt.com/"
languageCode = "en-us"
title = "Team Ranch BLT"
theme = "hugo-freelancer-theme"


[params]

    # You can use Markdown syntax for urls [text](//url.to/source) for
    # most longer texts.

    # To provide some metadata for search engines feel free to add a few
    # information about you and your website.
    name = "Team Ranch BLT"
    description = "Ranch BLT makes games."

    # Custom assets
	custom_css = ["css/custom.css"]
	custom_js  = []

    [params.navigation]
        brand = "Ranch BLT Portfolio"


    [params.header]
        # Copy your own image into './static/img/'' if you wish
        image = "avatar.png"
        name = "Team Ranch BLT"
        subtitle = "Ranch BLT makes games."


    [params.portfolio]
        # All projects defined in their own files. You can find example projects
        # at 'exampleSite/data/projects'. Copy the 'projects' folder into the 'data' directory
        # at the root of this Hugo site.
        # For more informtion take a look at the README.
        title = "Portfolio"

        [params.portfolio.modal]
            date = "Date"
            buttontext = "Close"
            buybuttontext = "Download Now"


    [params.about]
        title = "About"
        # The about text is splitted into a left and right column
        left = "John O’Malley - Programming<br>Kevin Tracy - Programming, Music<br>Mike Peppler - Programming, Sound"
        right = "Chris Reyes - Programming<br>Tom Enright - Programming<br>Jen Tracy - Art"

    [params.footer]
        copyright = "Published under the Apache License 2.0. Powered by [Hugo](//gohugo.io)."

        [params.footer.social]
            title = "Around the web"
            # All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
            # for more icons. The icons are represented by their corresponding
            # CSS class.
            [[params.footer.social.networks]]
                icon = "fa-github"
                link = "//github.com/ranchblt"

            [[params.footer.social.networks]]
                icon = "fa-twitter"
                link=  "//twitter.com/ranchblt"
            
            [[params.footer.social.networks]]
                icon = "fa-shopping-cart"
                link=  "//ranchblt.itch.io"
