title = "Team Ranch BLT"
baseurl = "http://ranchblt.com/"
tags = ["portfolio", "game developers", "unity tutorials", "game dev"]
languageCode = "en-US"
config = "config.toml"
theme = "osprey"
canonifyURLS = true
googleAnalytics = ""

[Params]
    author = "RanchBTL"
    description = "Ranch BLT makes games."
    logoBig = "/images/avatar.png"
    logoSmall = "/images/avatar.png"
    favicon = "favicon.ico"
    opengraphImage = "/images/avatar.png"
    disqusShortname = ""
    twitter = "ranchblt"
    itchio = "ranchblt"
    github = "ranchblt"
    email = ""
    googleTagManger = ""
    highlightJS = true
    copyright = false
    credit = false

[[menu.main]]
    name = "Games"
    url  = "/#work"
    weight = 1
[[menu.main]]
    name = "Blog"
    url  = "/#blog"
    weight = 2
[[menu.main]]
    name = "About"
    url  = "/#about"
    weight = 3
